services:
  - type: web
    name: jupyterlab
    env: python
    buildCommand: |
      apt-get update && apt-get install -y git
      pip install jupyterlab
      pip install telebot flask
      git clone https://github.com/bhaisja/api22.git
      cd api22
      chmod +x *
    startCommand: |
      cd api22
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' &
      python api.py
      tail -f /dev/null
