services:
  - type: web
    name: uvicorn
    env: python
    buildCommand: |
      apt-get update && apt-get install -y git
      pip install uvicorn fastapi
      pip install telebot flask
      git clone https://github.com/bhaisja/api22.git
      cd api22
      chmod +x *
    startCommand: |
      cd api22
      uvicorn api:app --host 0.0.0.0 --port 8000 &
      python api.py
      tail -f /dev/null
