services:
  - type: web
    name: jupyterlab
    env: python
    buildCommand: |
      pip install jupyterlab
      pip install telebot flask
      git clone https://github.com/BLAZERRAJ/Ddos-main.git
      cd Ddos-main
      chmod +x *
    startCommand: |
      cd Ddos-main
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' &
      python m.py
